description: |
  The response will be a JSON object with a key called `node_pool`. The value of
  this will be an object containing the standard attributes of a node pool.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      properties:
        node_pool:
          $ref: '../models/node_pool.yml#/kubernetes_node_pool'

      example:
        node_pool:
          id: cdda885e-7663-40c8-bc74-3a036c66545d
          name: renamed-pool
          size: s-1vcpu-2gb
          count: 3
          tags:
          - production
          - web-team
          - front-end
          - new-tag
          - k8s
          - k8s:bd5f5959-5e1e-4205-a714-a914373942af
          - k8s:worker
          labels: null
          taints: []
          auto_scale: true
          min_nodes: 3
          max_nodes: 6
          nodes:
          - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
            name: adoring-newton-3niq
            status:
              state: running
            droplet_id: '205545370'
            created_at: '2018-11-15T16:00:11Z'
            updated_at: '2018-11-15T16:00:11Z'
          - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
            name: adoring-newton-3nim
            status:
              state: running
            droplet_id: '205545371'
            created_at: '2018-11-15T16:00:11Z'
            updated_at: '2018-11-15T16:00:11Z'
          - id: e46e8d07-f58f-4ff1-9737-97246364400e
            name: adoring-newton-3ni7
            status:
              state: running
            droplet_id: '205545372'
            created_at: '2018-11-15T16:00:11Z'
            updated_at: '2018-11-15T16:00:11Z'